### ISSUE TITLE
'ascii' codec can't encode character '\u2026' in position 512: ordinal not in range(128)

### ISSUE THREAD

**Issue by KraetSpg** [st1vms/unofficial-claude-api#26] opened 2024-09-28 06:55 UTC
I get this issue when calling any of the clients methods. 
'ascii' codec can't encode character '\u2026' in position 512: ordinal not in range(128)

**Comment by st1vms** [comment] 2024-09-28 11:03
@KraetSpg Thanks for reaching out.

Unfortunately, I can't reproduce the issue on my end.

I may need to know the exact method throwing you this error, and the context of operation.

**Comment by st1vms** [comment] 2024-10-18 12:49
Closing this as not planned.

**Closed** 2024-10-18 12:49 UTC
Labels: invalid, wontfix, can't reproduce

**Comment by KraetSpg** [comment] 2024-10-18 19:34
Thanks, it was a random char in my cookie, I just deleted it and it worked.
